/*
 * Copyright (C) 2014 Chenko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package lvpd.tool;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Chenko
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        closeAboutDialog = new javax.swing.JButton();
        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        catLabelVehicular = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        catLabelLight = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        catLabelMedium = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox25 = new javax.swing.JCheckBox();
        firearmComboBox = new javax.swing.JComboBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        radioButtonCocaine = new javax.swing.JRadioButton();
        radioButtonSpeed = new javax.swing.JRadioButton();
        radioButtonPot = new javax.swing.JRadioButton();
        spinnerCocaine = new javax.swing.JSpinner();
        spinnerSpeed = new javax.swing.JSpinner();
        spinnerPot = new javax.swing.JSpinner();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        comboBoxTrafficking = new javax.swing.JComboBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        comboBoxDischarge = new javax.swing.JComboBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        mainMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuEditCrimes = new javax.swing.JMenuItem();
        menuToggleCursor = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuAboutDev = new javax.swing.JMenuItem();
        menuSupportDev = new javax.swing.JMenuItem();

        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        aboutDialog.setTitle("About the LVPD Tool");
        aboutDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutDialog.setFocusableWindowState(false);
        aboutDialog.setMinimumSize(new java.awt.Dimension(402, 300));
        aboutDialog.setType(java.awt.Window.Type.POPUP);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        aboutDialog.setLocation(dim.width/2-aboutDialog.getSize().width/2, dim.height/2-aboutDialog.getSize().height/2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LVPD Tool Version 3");

        jLabel2.setText("<html>\n\nThe LVPD Tool Version 3 was coded by Chenko for the MTG LVPD. This tool has many improvements from the first two versions including the ability to edit the times and fines of almost every crime. All of the data is stored in a SQLite database minimizing the harddrive footprint of the application while maximizing functionality. It also features extensive error logging and task logging to allow for quick and easy fixing of any problems that may arrise. \n<br><br>\nIf you wish to support the developer hit <b>About</b> and then <b>Support the Dev</b>");

        closeAboutDialog.setText("Close");
        closeAboutDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAboutDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addGroup(aboutDialogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(aboutDialogLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(closeAboutDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeAboutDialog)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(GlobalManager.APP_NAME + " | " + GlobalManager.VERSION + " | By " + GlobalManager.AUTHOR);
        setCursor(Toolkit.getDefaultToolkit().createCustomCursor(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Cursor.png")), new Point(getX(),
            getY()), "img"));
setIconImage(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Logo32.png")));

catLabelVehicular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelVehicular.setText("Vehicular Offences");

jCheckBox1.setText("Illegal Parking");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox1.getText()), jCheckBox1);

jCheckBox2.setText("Failure to Provide ID");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox2.getText()), jCheckBox2);

jCheckBox3.setText("Illegal Shortcut");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox3.getText()), jCheckBox3);

jCheckBox4.setText("Unlawful Hydraulics");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox4.getText()), jCheckBox4);

jCheckBox5.setText("Unlawful Nos");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox5.getText()), jCheckBox5);

jCheckBox6.setText("Reckless Driving");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox6.getText()), jCheckBox6);

jCheckBox7.setText("Reckless Endangerment");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox7.getText()), jCheckBox7);

jCheckBox8.setText("Street Racing");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox8.getText()), jCheckBox8);

jCheckBox9.setText("Driving w/o Due Care");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox9.getText()), jCheckBox9);

jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

catLabelLight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelLight.setText("Light Offences");

jCheckBox10.setText("Verbal Assualt");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox10.getText()), jCheckBox10);

jCheckBox11.setText("Loitering");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox11.getText()), jCheckBox11);

jCheckBox12.setText("Trespassing");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox12.getText()), jCheckBox12);

jCheckBox13.setText("Indecent Exposure");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox13.getText()), jCheckBox13);

jCheckBox14.setText("Lewd Gesture");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox14.getText()), jCheckBox14);

jCheckBox15.setText("Vandalism");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox15.getText()), jCheckBox15);

jCheckBox16.setText("Affray");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox16.getText()), jCheckBox16);

jCheckBox17.setText("Misuse of 911");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox17.getText()), jCheckBox17);

jCheckBox18.setText("Failure to Provide License");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox18.getText()), jCheckBox18);

jCheckBox19.setText("Resisting Arrest");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox19.getText()), jCheckBox19);

jCheckBox20.setText("Evading Arrest (Foot)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox20.getText()), jCheckBox20);

jCheckBox21.setText("Evading Arrest (Veh)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox21.getText()), jCheckBox21);

jCheckBox22.setText("Disorderly Conduct");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox22.getText()), jCheckBox22);

jCheckBox23.setText("Failure to Pay Ticket");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox23.getText()), jCheckBox23);

jCheckBox24.setText("Aiding & Abetting (Light)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox24.getText()), jCheckBox24);

catLabelMedium.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelMedium.setText("Medium Offences");

jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

jCheckBox25.setText("Firearm Possession");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox25.getText()), jCheckBox25);

firearmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Katana / Brass Knuckles", "Silenced", "Deagle", "Low Caliber", "High Caliber" }));

jCheckBox26.setText("Vehicular Assualt");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox26.getText()), jCheckBox26);

jCheckBox27.setText("Attempted GTA");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox27.getText()), jCheckBox27);

jCheckBox28.setText("Grand Theft Auto");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox28.getText()), jCheckBox28);

jCheckBox29.setText("DUI");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox29.getText()), jCheckBox29);

jCheckBox30.setText("Narcotics Possession");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox30.getText()), jCheckBox30);

radioButtonCocaine.setText("Cocaine");

radioButtonSpeed.setText("Speed");

radioButtonPot.setText("Pot");

jCheckBox31.setText("Impersonating LEO");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox31.getText()), jCheckBox31);

jCheckBox32.setText("Obstruction");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox32.getText()), jCheckBox32);

jCheckBox33.setText("Conspiracy");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox33.getText()), jCheckBox33);

jCheckBox34.setText("Hit & Run");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox34.getText()), jCheckBox34);

jCheckBox35.setText("Trafficking");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox35.getText()), jCheckBox35);

comboBoxTrafficking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Materials", "Firearms", "Narcotics" }));

jCheckBox36.setText("Harassment");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox36.getText()), jCheckBox36);

jCheckBox37.setText("Unlawful Discharge");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox37.getText()), jCheckBox37);

comboBoxDischarge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Multiple/Rapid" }));

jCheckBox38.setText("Public Endangerment");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox38.getText()), jCheckBox38);

jCheckBox39.setText("Fraud");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox39.getText()), jCheckBox39);

jCheckBox40.setText("Lying to an LEO");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox40.getText()), jCheckBox40);

jCheckBox41.setText("Driving whilst Suspended");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox41.getText()), jCheckBox41);

jCheckBox42.setText("Aiding & Abetting (Med)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox42.getText()), jCheckBox42);

jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
mainPanel.setLayout(mainPanelLayout);
mainPanelLayout.setHorizontalGroup(
    mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(mainPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox3)
            .addComponent(jCheckBox2)
            .addComponent(jCheckBox1)
            .addComponent(catLabelVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jCheckBox6)
            .addComponent(jCheckBox5)
            .addComponent(jCheckBox4)
            .addComponent(jCheckBox9)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jCheckBox8)))
        .addGap(18, 18, 18)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox24)
            .addComponent(jCheckBox23)
            .addComponent(jCheckBox22)
            .addComponent(jCheckBox21)
            .addComponent(jCheckBox20)
            .addComponent(catLabelLight, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jCheckBox10)
            .addComponent(jCheckBox11)
            .addComponent(jCheckBox12)
            .addComponent(jCheckBox13)
            .addComponent(jCheckBox14)
            .addComponent(jCheckBox15)
            .addComponent(jCheckBox16)
            .addComponent(jCheckBox17)
            .addComponent(jCheckBox18)
            .addComponent(jCheckBox19))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catLabelMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jCheckBox31)
            .addComponent(jCheckBox32)
            .addComponent(jCheckBox33)
            .addComponent(jCheckBox34)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox25)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firearmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioButtonCocaine)
                                    .addComponent(radioButtonSpeed)
                                    .addComponent(radioButtonPot))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinnerCocaine, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(spinnerSpeed)
                                    .addComponent(spinnerPot)))))
                    .addComponent(jCheckBox26)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox28)
                    .addComponent(jCheckBox29)
                    .addComponent(jCheckBox30))
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox39)
                    .addComponent(jCheckBox38)
                    .addComponent(jCheckBox35)
                    .addComponent(jCheckBox36)
                    .addComponent(jCheckBox37)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTrafficking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox40)
                    .addComponent(jCheckBox41)
                    .addComponent(jCheckBox42))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(451, Short.MAX_VALUE))
    );
    mainPanelLayout.setVerticalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addComponent(catLabelMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox25)
                        .addComponent(jCheckBox35))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firearmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxTrafficking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox36)
                        .addComponent(jCheckBox26))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox27)
                        .addComponent(jCheckBox37))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox28)
                        .addComponent(comboBoxDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox29)
                        .addComponent(jCheckBox38))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox30)
                        .addComponent(jCheckBox39))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonCocaine)
                        .addComponent(spinnerCocaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox40))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonSpeed)
                        .addComponent(spinnerSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox41))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonPot)
                        .addComponent(spinnerPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox42))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox31)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox32)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox33)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox34))
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(catLabelLight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox19))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(catLabelVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox9)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox20)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox21)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox24))
                .addComponent(jSeparator2)
                .addComponent(jSeparator4))
            .addContainerGap(313, Short.MAX_VALUE))
    );

    catLabelVehicular.getAccessibleContext().setAccessibleDescription("");

    mainScrollPane.setViewportView(mainPanel);

    menuFile.setText("File");

    menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
    menuExit.setText("Exit");
    menuExit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuExitActionPerformed(evt);
        }
    });
    menuFile.add(menuExit);

    mainMenuBar.add(menuFile);

    menuHelp.setText("Edit");

    menuEditCrimes.setText("Edit Crimes");
    menuEditCrimes.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuEditCrimesActionPerformed(evt);
        }
    });
    menuHelp.add(menuEditCrimes);

    menuToggleCursor.setText("Toggle Custom Cursor");
    menuToggleCursor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuToggleCursorActionPerformed(evt);
        }
    });
    menuHelp.add(menuToggleCursor);

    mainMenuBar.add(menuHelp);

    menuAbout.setText("About");

    menuAboutDev.setText("About the LVPD Tool");
    menuAboutDev.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuAboutDevActionPerformed(evt);
        }
    });
    menuAbout.add(menuAboutDev);

    menuSupportDev.setText("Support the Dev");
    menuSupportDev.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuSupportDevActionPerformed(evt);
        }
    });
    menuAbout.add(menuSupportDev);

    mainMenuBar.add(menuAbout);

    setJMenuBar(mainMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainScrollPane)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainScrollPane)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuEditCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditCrimesActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuEditCrimesActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAboutDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutDevActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuAboutDevActionPerformed

    private void menuSupportDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupportDevActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuSupportDevActionPerformed

    private void menuToggleCursorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToggleCursorActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuToggleCursorActionPerformed

    private void closeAboutDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAboutDialogActionPerformed
        aboutDialog.setVisible(false);
    }//GEN-LAST:event_closeAboutDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    public static void initGui() {
        Logger.Logger("Initializing GUI...");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog aboutDialog;
    public javax.swing.JLabel catLabelLight;
    public javax.swing.JLabel catLabelMedium;
    public javax.swing.JLabel catLabelVehicular;
    public javax.swing.JButton closeAboutDialog;
    public javax.swing.JComboBox comboBoxDischarge;
    public javax.swing.JComboBox comboBoxTrafficking;
    public javax.swing.JComboBox firearmComboBox;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox10;
    public javax.swing.JCheckBox jCheckBox11;
    public javax.swing.JCheckBox jCheckBox12;
    public javax.swing.JCheckBox jCheckBox13;
    public javax.swing.JCheckBox jCheckBox14;
    public javax.swing.JCheckBox jCheckBox15;
    public javax.swing.JCheckBox jCheckBox16;
    public javax.swing.JCheckBox jCheckBox17;
    public javax.swing.JCheckBox jCheckBox18;
    public javax.swing.JCheckBox jCheckBox19;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox20;
    public javax.swing.JCheckBox jCheckBox21;
    public javax.swing.JCheckBox jCheckBox22;
    public javax.swing.JCheckBox jCheckBox23;
    public javax.swing.JCheckBox jCheckBox24;
    public javax.swing.JCheckBox jCheckBox25;
    public javax.swing.JCheckBox jCheckBox26;
    public javax.swing.JCheckBox jCheckBox27;
    public javax.swing.JCheckBox jCheckBox28;
    public javax.swing.JCheckBox jCheckBox29;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox30;
    public javax.swing.JCheckBox jCheckBox31;
    public javax.swing.JCheckBox jCheckBox32;
    public javax.swing.JCheckBox jCheckBox33;
    public javax.swing.JCheckBox jCheckBox34;
    public javax.swing.JCheckBox jCheckBox35;
    public javax.swing.JCheckBox jCheckBox36;
    public javax.swing.JCheckBox jCheckBox37;
    public javax.swing.JCheckBox jCheckBox38;
    public javax.swing.JCheckBox jCheckBox39;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JCheckBox jCheckBox40;
    public javax.swing.JCheckBox jCheckBox41;
    public javax.swing.JCheckBox jCheckBox42;
    public javax.swing.JCheckBox jCheckBox5;
    public javax.swing.JCheckBox jCheckBox6;
    public javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JCheckBox jCheckBox8;
    public javax.swing.JCheckBox jCheckBox9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JMenuBar mainMenuBar;
    public static javax.swing.JPanel mainPanel;
    public javax.swing.JScrollPane mainScrollPane;
    public javax.swing.JMenu menuAbout;
    public javax.swing.JMenuItem menuAboutDev;
    public javax.swing.JMenuItem menuEditCrimes;
    public javax.swing.JMenuItem menuExit;
    public javax.swing.JMenu menuFile;
    public javax.swing.JMenu menuHelp;
    public javax.swing.JMenuItem menuSupportDev;
    public javax.swing.JMenuItem menuToggleCursor;
    public javax.swing.JRadioButton radioButtonCocaine;
    public javax.swing.JRadioButton radioButtonPot;
    public javax.swing.JRadioButton radioButtonSpeed;
    public javax.swing.JSpinner spinnerCocaine;
    public javax.swing.JSpinner spinnerPot;
    public javax.swing.JSpinner spinnerSpeed;
    // End of variables declaration//GEN-END:variables
}
