/*
 * Copyright (C) 2014 Chenko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package lvpd.tool;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.DefaultListModel;

/**
 *
 * @author Chenko
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        closeAboutDialog = new javax.swing.JButton();
        consoleFrame = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaConsole = new javax.swing.JTextArea();
        buttonCopyConsole = new javax.swing.JButton();
        buttonCloseWindow = new javax.swing.JToggleButton();
        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        catLabelVehicular = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        catLabelLight = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        catLabelMedium = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox25 = new javax.swing.JCheckBox();
        firearmComboBox = new javax.swing.JComboBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        radioButtonCocaine = new javax.swing.JRadioButton();
        radioButtonSpeed = new javax.swing.JRadioButton();
        radioButtonPot = new javax.swing.JRadioButton();
        spinnerCocaine = new javax.swing.JSpinner();
        spinnerSpeed = new javax.swing.JSpinner();
        spinnerPot = new javax.swing.JSpinner();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        comboBoxTrafficking = new javax.swing.JComboBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        comboBoxDischarge = new javax.swing.JComboBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        catLabelHeavy = new javax.swing.JLabel();
        jCheckBox43 = new javax.swing.JCheckBox();
        radioButtonAttemptedMurder = new javax.swing.JRadioButton();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        radioButtonKidnapping = new javax.swing.JRadioButton();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        catLabelCapital = new javax.swing.JLabel();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        radioButtonMurder = new javax.swing.JRadioButton();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jSeparator6 = new javax.swing.JSeparator();
        catLabelEditCrime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editCrimeList = new javax.swing.JList();
        editCrimeSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textFieldTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldFine = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldStrikes = new javax.swing.JTextField();
        editCrimeSave = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        catLabeLimits = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textMaxTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textMaxFine = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textMaxStrikes = new javax.swing.JTextField();
        editCrimeSave1 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        catLabeLimits1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinnerPlayerID = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        buttonCalculate = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        catLabeLimits2 = new javax.swing.JLabel();
        labelResults = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textCommand = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        spinnerMats = new javax.swing.JSpinner();
        radioButtonAssault = new javax.swing.JRadioButton();
        mainMenuBar = new javax.swing.JMenuBar();
        menuStats = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuToggleCursor = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuAboutDev = new javax.swing.JMenuItem();
        menuSupportDev = new javax.swing.JMenuItem();

        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        aboutDialog.setTitle("About the LVPD Tool");
        aboutDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutDialog.setFocusableWindowState(false);
        aboutDialog.setIconImage(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Logo32.png")));
        aboutDialog.setMinimumSize(new java.awt.Dimension(402, 300));
        aboutDialog.setResizable(false);
        aboutDialog.setType(java.awt.Window.Type.POPUP);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        aboutDialog.setLocation(dim.width/2-aboutDialog.getSize().width/2, dim.height/2-aboutDialog.getSize().height/2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LVPD Tool Version 3");

        jLabel2.setText("<html>\n\nThe LVPD Tool Version 3 was coded by Chenko for the MTG LVPD. This tool has many improvements from the first two versions including the ability to edit the times and fines of almost every crime. All of the data is stored in a SQLite database minimizing the harddrive footprint of the application while maximizing functionality. It also features extensive error logging and task logging to allow for quick and easy fixing of any problems that may arrise. \n<br><br>\nIf you wish to support the developer hit <b>About</b> and then <b>Support the Dev</b>");

        closeAboutDialog.setText("Close");
        closeAboutDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAboutDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addGroup(aboutDialogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(aboutDialogLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(closeAboutDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeAboutDialog)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        consoleFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        consoleFrame.setTitle("Console");
        consoleFrame.setIconImage(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Logo32.png")));
        consoleFrame.setMinimumSize(new java.awt.Dimension(900, 530));
        consoleFrame.setResizable(false);

        textAreaConsole.setEditable(false);
        textAreaConsole.setColumns(20);
        textAreaConsole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textAreaConsole.setRows(5);
        jScrollPane2.setViewportView(textAreaConsole);

        buttonCopyConsole.setText("Copy to Clipboard");
        buttonCopyConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCopyConsoleActionPerformed(evt);
            }
        });

        buttonCloseWindow.setText("Close Window");
        buttonCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consoleFrameLayout = new javax.swing.GroupLayout(consoleFrame.getContentPane());
        consoleFrame.getContentPane().setLayout(consoleFrameLayout);
        consoleFrameLayout.setHorizontalGroup(
            consoleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consoleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(consoleFrameLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(buttonCopyConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(buttonCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consoleFrameLayout.setVerticalGroup(
            consoleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consoleFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consoleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCopyConsole)
                    .addComponent(buttonCloseWindow))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(GlobalManager.APP_NAME + " | " + GlobalManager.VERSION + " | By " + GlobalManager.AUTHOR);
        setCursor(Toolkit.getDefaultToolkit().createCustomCursor(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Cursor.png")), new Point(getX(),
            getY()), "img"));
setIconImage(Toolkit.getDefaultToolkit().getImage(MainGUI.class.getResource("resources/images/Logo32.png")));

catLabelVehicular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelVehicular.setText("Vehicular Offences");

jCheckBox1.setText("Illegal Parking");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox1.getText()), jCheckBox1);

jCheckBox2.setText("Failure to Provide Reg");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox2.getText()), jCheckBox2);

jCheckBox3.setText("Illegal Shortcut");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox3.getText()), jCheckBox3);

jCheckBox4.setText("Unlawful Hydraulics");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox4.getText()), jCheckBox4);

jCheckBox5.setText("Unlawful Nos");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox5.getText()), jCheckBox5);

jCheckBox6.setText("Reckless Driving");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox6.getText()), jCheckBox6);

jCheckBox7.setText("Reckless Endangerment");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox7.getText()), jCheckBox7);

jCheckBox8.setText("Street Racing");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox8.getText()), jCheckBox8);

jCheckBox9.setText("Driving w/o Due Care");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox9.getText()), jCheckBox9);

jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

catLabelLight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelLight.setText("Light Offences");

jCheckBox10.setText("Verbal Assault");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox10.getText()), jCheckBox10);

jCheckBox11.setText("Loitering");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox11.getText()), jCheckBox11);

jCheckBox12.setText("Trespassing");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox12.getText()), jCheckBox12);

jCheckBox13.setText("Indecent Exposure");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox13.getText()), jCheckBox13);

jCheckBox14.setText("Lewd Gesture");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox14.getText()), jCheckBox14);

jCheckBox15.setText("Vandalism");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox15.getText()), jCheckBox15);

jCheckBox16.setText("Affray");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox16.getText()), jCheckBox16);

jCheckBox17.setText("Misuse of 911");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox17.getText()), jCheckBox17);

jCheckBox18.setText("Failure to Provide License");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox18.getText()), jCheckBox18);

jCheckBox19.setText("Resisting Arrest");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox19.getText()), jCheckBox19);

jCheckBox20.setText("Evading Arrest (Foot)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox20.getText()), jCheckBox20);

jCheckBox21.setText("Evading Arrest (Veh)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox21.getText()), jCheckBox21);

jCheckBox22.setText("Disorderly Conduct");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox22.getText()), jCheckBox22);

jCheckBox23.setText("Failure to Pay Ticket");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox23.getText()), jCheckBox23);

jCheckBox24.setText("Aiding & Abetting (Light)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox24.getText()), jCheckBox24);

catLabelMedium.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelMedium.setText("Medium Offences");

jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

jCheckBox25.setText("Firearm Possession");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox25.getText()), jCheckBox25);

firearmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Katana / Brass Knuckles", "Silenced", "Deagle", "Low Caliber", "High Caliber" }));

jCheckBox26.setText("Vehicular Assault");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox26.getText()), jCheckBox26);

jCheckBox27.setText("Attempted GTA");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox27.getText()), jCheckBox27);

jCheckBox28.setText("Grand Theft Auto");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox28.getText()), jCheckBox28);

jCheckBox29.setText("DUI");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox29.getText()), jCheckBox29);

jCheckBox30.setText("Narcotics Possession");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox30.getText()), jCheckBox30);

radioButtonCocaine.setText("Cocaine");

radioButtonSpeed.setText("Speed");

radioButtonPot.setText("Pot");

jCheckBox31.setText("Impersonating LEO");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox31.getText()), jCheckBox31);

jCheckBox32.setText("Obstruction");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox32.getText()), jCheckBox32);

jCheckBox33.setText("Conspiracy");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox33.getText()), jCheckBox33);

jCheckBox34.setText("Hit & Run");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox34.getText()), jCheckBox34);

jCheckBox35.setText("Trafficking");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox35.getText()), jCheckBox35);

comboBoxTrafficking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Materials", "Firearms", "Narcotics" }));

jCheckBox36.setText("Harassment");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox36.getText()), jCheckBox36);

jCheckBox37.setText("Unlawful Discharge");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox37.getText()), jCheckBox37);

comboBoxDischarge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Multiple" }));

jCheckBox38.setText("Public Endangerment");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox38.getText()), jCheckBox38);

jCheckBox39.setText("Fraud");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox39.getText()), jCheckBox39);

jCheckBox40.setText("Lying to an LEO");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox40.getText()), jCheckBox40);

jCheckBox41.setText("Driving whilst Suspended");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox41.getText()), jCheckBox41);

jCheckBox42.setText("Aiding & Abetting (Med)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox42.getText()), jCheckBox42);

jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

catLabelHeavy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelHeavy.setText("Heavy Offences");

jCheckBox43.setText("Attempted Murder");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox43.getText()), jCheckBox43);

radioButtonAttemptedMurder.setText("<html><i>Of an LEO");

jCheckBox44.setText("Instigating Anarchy");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox44.getText()), jCheckBox44);

jCheckBox45.setText("Kidnapping");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox45.getText()), jCheckBox45);

radioButtonKidnapping.setText("<html><i>Of an LEO");

jCheckBox46.setText("Racketeering");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox46.getText()), jCheckBox46);

jCheckBox47.setText("Armed Robbery");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox47.getText()), jCheckBox47);

jCheckBox48.setText("Illegal Gambling");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox48.getText()), jCheckBox48);

jCheckBox49.setText("Bribery");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox49.getText()), jCheckBox49);

jCheckBox50.setText("Assault");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox50.getText()), jCheckBox50);

jCheckBox51.setText("Assault & Battery");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox51.getText()), jCheckBox51);

jCheckBox52.setText("Assault w/ Deadly Weapon");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox52.getText()), jCheckBox52);

jCheckBox53.setText("Extortion");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox53.getText()), jCheckBox53);

jCheckBox54.setText("Scamming");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox54.getText()), jCheckBox54);

jCheckBox55.setText("Arson");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox55.getText()), jCheckBox55);

jCheckBox56.setText("Aiding & Abetting (Heavy)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox56.getText()), jCheckBox56);

jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

catLabelCapital.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelCapital.setText("Capital Offences");

jCheckBox57.setText("Terrorism");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox57.getText()), jCheckBox57);

jCheckBox58.setText("Successful Murder");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox58.getText()), jCheckBox58);

radioButtonMurder.setText("<html><i>Of an LEO");

jCheckBox59.setText("Mass Murder");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox59.getText()), jCheckBox59);

jCheckBox60.setText("Police Corruption");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox60.getText()), jCheckBox60);

jCheckBox61.setText("Piracy (Sea)");
CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox61.getText()), jCheckBox61);

catLabelEditCrime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
catLabelEditCrime.setText("Edit Crime");

DefaultListModel listModel = new DefaultListModel<String>();
for(String key : CrimeManager.crimeObjects.keySet()) {
    listModel.addElement(key);
    }
    editCrimeList.setModel(listModel);
    editCrimeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            editCrimeListValueChanged(evt);
        }
    });
    jScrollPane1.setViewportView(editCrimeList);

    jButton1.setText("Search");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jLabel3.setText("<html><b>Time");

    jLabel4.setText("<html><b>Fine");

    jLabel5.setText("<html><b>Strikes");

    editCrimeSave.setText("Save Changes");
    editCrimeSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editCrimeSaveActionPerformed(evt);
        }
    });

    jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

    catLabeLimits.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    catLabeLimits.setText("Crime Limits");

    jLabel6.setText("<html><b>Max Time");

    jLabel7.setText("<html><b>Max Fine");

    jLabel8.setText("<html><b>Max Strikes");

    editCrimeSave1.setText("Save Changes");
    editCrimeSave1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editCrimeSave1ActionPerformed(evt);
        }
    });

    jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

    catLabeLimits1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    catLabeLimits1.setText("Calculate");

    jLabel9.setText("<html><b>Playerid: ");

    jLabel10.setText("<html><b>Criminal Name:");

    textFieldName.setText("No underscore ");

    buttonCalculate.setText("<html><b><font color = \"blue\">Calculate");
    buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonCalculateActionPerformed(evt);
        }
    });

    buttonReset.setText("<html><b><font color = \"red\">Reset");
    buttonReset.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonResetActionPerformed(evt);
        }
    });

    catLabeLimits2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    catLabeLimits2.setText("Results");

    labelResults.setText("<html><b>Fine:</b> $0<br><br><b>Time: </b>0 minutes<br><br><b>Strikes: </b>0");

    jLabel12.setText("<html><b>Command:");

    textCommand.setEditable(false);

    jButton2.setText("Copy to Clipboard");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jCheckBox62.setText("Robbery");
    CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox62.getText()), jCheckBox62);

    jCheckBox63.setText("Materials Possession");
    CrimeManager.addCheckBox(CrimeManager.getCrimeObjectByName(jCheckBox63.getText()), jCheckBox63);

    radioButtonAssault.setText("<html><i>Of an LEO");

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox3)
                                .addComponent(jCheckBox2)
                                .addComponent(jCheckBox1)
                                .addComponent(catLabelVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox6)
                                .addComponent(jCheckBox5)
                                .addComponent(jCheckBox4)
                                .addComponent(jCheckBox9)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox8)))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox24)
                                .addComponent(jCheckBox23)
                                .addComponent(jCheckBox22)
                                .addComponent(jCheckBox21)
                                .addComponent(jCheckBox20)
                                .addComponent(catLabelLight, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox10)
                                .addComponent(jCheckBox11)
                                .addComponent(jCheckBox12)
                                .addComponent(jCheckBox13)
                                .addComponent(jCheckBox14)
                                .addComponent(jCheckBox15)
                                .addComponent(jCheckBox16)
                                .addComponent(jCheckBox17)
                                .addComponent(jCheckBox18)
                                .addComponent(jCheckBox19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catLabelMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox33)
                                .addComponent(jCheckBox34)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox25)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(firearmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(radioButtonCocaine)
                                                        .addComponent(radioButtonSpeed)
                                                        .addComponent(radioButtonPot))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(spinnerCocaine, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                                        .addComponent(spinnerSpeed)
                                                        .addComponent(spinnerPot)))))
                                        .addComponent(jCheckBox26)
                                        .addComponent(jCheckBox27)
                                        .addComponent(jCheckBox28)
                                        .addComponent(jCheckBox29)
                                        .addComponent(jCheckBox30)
                                        .addComponent(jCheckBox31)
                                        .addComponent(jCheckBox32))
                                    .addGap(19, 19, 19)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox63)
                                        .addComponent(jCheckBox39)
                                        .addComponent(jCheckBox38)
                                        .addComponent(jCheckBox35)
                                        .addComponent(jCheckBox36)
                                        .addComponent(jCheckBox37)
                                        .addComponent(jCheckBox40)
                                        .addComponent(jCheckBox41)
                                        .addComponent(jCheckBox42)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comboBoxDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(comboBoxTrafficking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(spinnerMats, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(catLabelHeavy, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox44)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(radioButtonAttemptedMurder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCheckBox43)
                                .addComponent(jCheckBox45)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(radioButtonKidnapping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCheckBox46)
                                .addComponent(jCheckBox47)
                                .addComponent(jCheckBox48)
                                .addComponent(jCheckBox49)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(jCheckBox50)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioButtonAssault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCheckBox51)
                                .addComponent(jCheckBox52)
                                .addComponent(jCheckBox53)
                                .addComponent(jCheckBox54)
                                .addComponent(jCheckBox55)
                                .addComponent(jCheckBox56))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catLabelCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox57)
                                .addComponent(jCheckBox58)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(radioButtonMurder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCheckBox59)
                                .addComponent(jCheckBox60)
                                .addComponent(jCheckBox61)
                                .addComponent(jCheckBox62))
                            .addGap(0, 61, Short.MAX_VALUE))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(catLabelEditCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(editCrimeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldFine, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldStrikes)
                                .addComponent(editCrimeSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldTime))))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(catLabeLimits, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textMaxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textMaxFine, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textMaxStrikes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editCrimeSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catLabeLimits1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(spinnerPlayerID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textFieldName))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(42, 42, 42)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelResults, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(catLabeLimits2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addGap(193, 193, 193))))))
    );
    mainPanelLayout.setVerticalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(catLabelCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox57)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox58)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioButtonMurder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox59)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox60)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox61)
                            .addGap(1, 1, 1)
                            .addComponent(jCheckBox62))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(catLabelHeavy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonAttemptedMurder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonKidnapping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox50)
                                    .addComponent(radioButtonAssault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox56))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(catLabelMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox25)
                                    .addComponent(jCheckBox35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firearmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxTrafficking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox36)
                                    .addComponent(jCheckBox26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox27)
                                    .addComponent(jCheckBox37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox28)
                                    .addComponent(comboBoxDischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox29)
                                    .addComponent(jCheckBox38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox30)
                                    .addComponent(jCheckBox39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioButtonCocaine)
                                    .addComponent(spinnerCocaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox40))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioButtonSpeed)
                                    .addComponent(spinnerSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox41))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioButtonPot)
                                    .addComponent(spinnerPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox31)
                                    .addComponent(jCheckBox63))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox32)
                                    .addComponent(spinnerMats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox34))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(catLabelLight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox19))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(catLabelVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox24))
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGap(18, 18, 18)
            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldStrikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editCrimeSave))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(catLabelEditCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editCrimeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap(111, Short.MAX_VALUE))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(catLabeLimits, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textMaxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textMaxFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textMaxStrikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(editCrimeSave1))
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(catLabeLimits1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(catLabeLimits2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(3, 3, 3)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spinnerPlayerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(labelResults)))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );

    catLabelVehicular.getAccessibleContext().setAccessibleDescription("");

    mainScrollPane.setViewportView(mainPanel);

    menuStats.setText("File");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem1.setText("Stats");
    menuStats.add(jMenuItem1);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("Show Console");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    menuStats.add(jMenuItem2);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("Open Logs Directory");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    menuStats.add(jMenuItem3);

    menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
    menuExit.setText("Exit");
    menuExit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuExitActionPerformed(evt);
        }
    });
    menuStats.add(menuExit);

    mainMenuBar.add(menuStats);

    menuHelp.setText("Edit");

    menuToggleCursor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
    menuToggleCursor.setText("Toggle Custom Cursor");
    menuToggleCursor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuToggleCursorActionPerformed(evt);
        }
    });
    menuHelp.add(menuToggleCursor);

    mainMenuBar.add(menuHelp);

    menuAbout.setText("About");

    menuAboutDev.setText("About the LVPD Tool");
    menuAboutDev.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuAboutDevActionPerformed(evt);
        }
    });
    menuAbout.add(menuAboutDev);

    menuSupportDev.setText("Support the Dev");
    menuSupportDev.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuSupportDevActionPerformed(evt);
        }
    });
    menuAbout.add(menuSupportDev);

    mainMenuBar.add(menuAbout);

    setJMenuBar(mainMenuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainScrollPane)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainScrollPane)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAboutDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutDevActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuAboutDevActionPerformed

    private void menuSupportDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupportDevActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuSupportDevActionPerformed

    private void menuToggleCursorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToggleCursorActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_menuToggleCursorActionPerformed

    private void closeAboutDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAboutDialogActionPerformed
        aboutDialog.setVisible(false);
    }//GEN-LAST:event_closeAboutDialogActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void buttonCopyConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCopyConsoleActionPerformed
        StringSelection stringSelection = new StringSelection(textAreaConsole.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, stringSelection);
        Logger.Logger("Copied console text to clipboard");
    }//GEN-LAST:event_buttonCopyConsoleActionPerformed

    private void buttonCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseWindowActionPerformed
        consoleFrame.setVisible(false);
        Logger.Logger("Closed console window");
    }//GEN-LAST:event_buttonCloseWindowActionPerformed

    private void editCrimeSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCrimeSave1ActionPerformed
        GlobalManager.MaxTime = Integer.parseInt(textMaxTime.getText());
        GlobalManager.MaxFine = Integer.parseInt(textMaxFine.getText());
        GlobalManager.MaxStrikes = Integer.parseInt(textMaxStrikes.getText());
        Database.saveGeneral();
        Logger.Logger("Edited crime limits");
    }//GEN-LAST:event_editCrimeSave1ActionPerformed

    private void editCrimeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCrimeSaveActionPerformed
        CrimeObject crime = CrimeManager.getCrimeObjectByName(MainGUI.editCrimeList.getSelectedValue().toString());
        crime.crimeSetTime(Integer.parseInt(MainGUI.textFieldTime.getText()));
        crime.crimeSetFine(Integer.parseInt(MainGUI.textFieldFine.getText()));
        crime.crimeSetStrikes(Integer.parseInt(MainGUI.textFieldStrikes.getText()));
        CrimeManager.updateToolTip(crime);
        Database.saveCrime(crime);
        Logger.Logger("Edit crime " + crime.crimeGetName());
    }//GEN-LAST:event_editCrimeSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String search = editCrimeSearch.getText();
        int index = 0;
        for(String key : CrimeManager.crimeObjects.keySet()) {
            if(key.toLowerCase().contains(search.toLowerCase())) {
                textFieldTime.setText(Integer.toString(CrimeManager.crimeObjects.get(key).crimeGetTime()));
                textFieldFine.setText(Integer.toString(CrimeManager.crimeObjects.get(key).crimeGetFine()));
                textFieldStrikes.setText(Integer.toString(CrimeManager.crimeObjects.get(key).crimeGetStrikes()));
                Logger.Logger("Searched for " + search + " and found " + CrimeManager.crimeObjects.get(key).crimeGetName());
                break;
            }
            index ++;
        }
        MainGUI.editCrimeList.setSelectedIndex(index);
        MainGUI.editCrimeList.ensureIndexIsVisible(index);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editCrimeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_editCrimeListValueChanged
        CrimeObject crime = CrimeManager.getCrimeObjectByName(editCrimeList.getSelectedValue().toString());
        textFieldTime.setText(Integer.toString(crime.crimeGetTime()));
        textFieldFine.setText(Integer.toString(crime.crimeGetFine()));
        textFieldStrikes.setText(Integer.toString(crime.crimeGetStrikes()));
        Logger.Logger("Load crime variables to text fields");
    }//GEN-LAST:event_editCrimeListValueChanged

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StringSelection stringSelection = new StringSelection(textCommand.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, stringSelection);
        Logger.Logger("Copied command text to clipboard.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ActionManager.OnAction(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    public static void initGui() {
        Logger.Logger("Initializing GUI...");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDialog aboutDialog;
    public javax.swing.JButton buttonCalculate;
    public javax.swing.JToggleButton buttonCloseWindow;
    public javax.swing.JButton buttonCopyConsole;
    public javax.swing.JButton buttonReset;
    public javax.swing.JLabel catLabeLimits;
    public javax.swing.JLabel catLabeLimits1;
    public javax.swing.JLabel catLabeLimits2;
    public javax.swing.JLabel catLabelCapital;
    public javax.swing.JLabel catLabelEditCrime;
    public javax.swing.JLabel catLabelHeavy;
    public javax.swing.JLabel catLabelLight;
    public javax.swing.JLabel catLabelMedium;
    public javax.swing.JLabel catLabelVehicular;
    public javax.swing.JButton closeAboutDialog;
    public static javax.swing.JComboBox comboBoxDischarge;
    public static javax.swing.JComboBox comboBoxTrafficking;
    public static javax.swing.JFrame consoleFrame;
    public static javax.swing.JList editCrimeList;
    public javax.swing.JButton editCrimeSave;
    public javax.swing.JButton editCrimeSave1;
    public static javax.swing.JTextField editCrimeSearch;
    public static javax.swing.JComboBox firearmComboBox;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox10;
    public javax.swing.JCheckBox jCheckBox11;
    public javax.swing.JCheckBox jCheckBox12;
    public javax.swing.JCheckBox jCheckBox13;
    public javax.swing.JCheckBox jCheckBox14;
    public javax.swing.JCheckBox jCheckBox15;
    public javax.swing.JCheckBox jCheckBox16;
    public javax.swing.JCheckBox jCheckBox17;
    public javax.swing.JCheckBox jCheckBox18;
    public javax.swing.JCheckBox jCheckBox19;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox20;
    public javax.swing.JCheckBox jCheckBox21;
    public javax.swing.JCheckBox jCheckBox22;
    public javax.swing.JCheckBox jCheckBox23;
    public javax.swing.JCheckBox jCheckBox24;
    public javax.swing.JCheckBox jCheckBox25;
    public javax.swing.JCheckBox jCheckBox26;
    public javax.swing.JCheckBox jCheckBox27;
    public javax.swing.JCheckBox jCheckBox28;
    public javax.swing.JCheckBox jCheckBox29;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox30;
    public javax.swing.JCheckBox jCheckBox31;
    public javax.swing.JCheckBox jCheckBox32;
    public javax.swing.JCheckBox jCheckBox33;
    public javax.swing.JCheckBox jCheckBox34;
    public javax.swing.JCheckBox jCheckBox35;
    public javax.swing.JCheckBox jCheckBox36;
    public javax.swing.JCheckBox jCheckBox37;
    public javax.swing.JCheckBox jCheckBox38;
    public javax.swing.JCheckBox jCheckBox39;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JCheckBox jCheckBox40;
    public javax.swing.JCheckBox jCheckBox41;
    public javax.swing.JCheckBox jCheckBox42;
    public javax.swing.JCheckBox jCheckBox43;
    public javax.swing.JCheckBox jCheckBox44;
    public javax.swing.JCheckBox jCheckBox45;
    public javax.swing.JCheckBox jCheckBox46;
    public javax.swing.JCheckBox jCheckBox47;
    public javax.swing.JCheckBox jCheckBox48;
    public javax.swing.JCheckBox jCheckBox49;
    public javax.swing.JCheckBox jCheckBox5;
    public javax.swing.JCheckBox jCheckBox50;
    public javax.swing.JCheckBox jCheckBox51;
    public javax.swing.JCheckBox jCheckBox52;
    public javax.swing.JCheckBox jCheckBox53;
    public javax.swing.JCheckBox jCheckBox54;
    public javax.swing.JCheckBox jCheckBox55;
    public javax.swing.JCheckBox jCheckBox56;
    public javax.swing.JCheckBox jCheckBox57;
    public javax.swing.JCheckBox jCheckBox58;
    public javax.swing.JCheckBox jCheckBox59;
    public javax.swing.JCheckBox jCheckBox6;
    public javax.swing.JCheckBox jCheckBox60;
    public javax.swing.JCheckBox jCheckBox61;
    public javax.swing.JCheckBox jCheckBox62;
    public javax.swing.JCheckBox jCheckBox63;
    public javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JCheckBox jCheckBox8;
    public javax.swing.JCheckBox jCheckBox9;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JSeparator jSeparator8;
    public javax.swing.JSeparator jSeparator9;
    public static javax.swing.JLabel labelResults;
    public javax.swing.JMenuBar mainMenuBar;
    public static javax.swing.JPanel mainPanel;
    public javax.swing.JScrollPane mainScrollPane;
    public javax.swing.JMenu menuAbout;
    public javax.swing.JMenuItem menuAboutDev;
    public javax.swing.JMenuItem menuExit;
    public javax.swing.JMenu menuHelp;
    public javax.swing.JMenu menuStats;
    public javax.swing.JMenuItem menuSupportDev;
    public javax.swing.JMenuItem menuToggleCursor;
    public static javax.swing.JRadioButton radioButtonAssault;
    public static javax.swing.JRadioButton radioButtonAttemptedMurder;
    public static javax.swing.JRadioButton radioButtonCocaine;
    public static javax.swing.JRadioButton radioButtonKidnapping;
    public static javax.swing.JRadioButton radioButtonMurder;
    public static javax.swing.JRadioButton radioButtonPot;
    public static javax.swing.JRadioButton radioButtonSpeed;
    public static javax.swing.JSpinner spinnerCocaine;
    public static javax.swing.JSpinner spinnerMats;
    public static javax.swing.JSpinner spinnerPlayerID;
    public static javax.swing.JSpinner spinnerPot;
    public static javax.swing.JSpinner spinnerSpeed;
    public static javax.swing.JTextArea textAreaConsole;
    public static javax.swing.JTextField textCommand;
    public static javax.swing.JTextField textFieldFine;
    public static javax.swing.JTextField textFieldName;
    public static javax.swing.JTextField textFieldStrikes;
    public static javax.swing.JTextField textFieldTime;
    public static javax.swing.JTextField textMaxFine;
    public static javax.swing.JTextField textMaxStrikes;
    public static javax.swing.JTextField textMaxTime;
    // End of variables declaration//GEN-END:variables
}
